CREATE DATABASE IF NOT EXISTS REALTIME_ANALYTICS;
USE DATABASE REALTIME_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE WAREHOUSE IF NOT EXISTS STREAMING_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

